type Engineer {
  id: ID!
  name: String!
  title: String!
  alias: String!
  team: String!
}

type Query {
  engineers: [Engineer]!
  engineer(input: EngineerInput): [Engineer]!
}

input EngineerInput {
  id: ID
  name: String
  title: String
  alias: String
  team: String
}

input NewEngineerInput {
  id: ID!
  name: String!
  title: String!
  alias: String!
  team: String!
}

type Mutation {
  newEngineer(input: NewEngineerInput!): [Engineer]!
}



{
  engineer(input: {alias: "yixwan"}) {
    name
    id
    case {
      id
      contract
    }
  }
}


http://restexample.com/api/getEngineerbyAlias/yixwan

http://restexample.com/api/getCaseById/eead52-asdwq2d-dsasd2-dsaf92/